[versions]
agp = "8.3.0"
kotlin = "1.8.10"
coreKtx = "1.12.0"
gms = "4.4.2"
ktfmt = "0.17.0"
appcompat = "1.6.1"
material = "1.11.0"
composeBom = "2024.02.02"
composeActivity = "1.8.2"
composeViewModel = "2.7.0"
lifecycleRuntimeKtx = "2.7.0"
sonar = "4.4.1.3373"

# UI Compose
mockitoAndroid = "5.13.0"
ui = "1.6.8"
uiTestJunit4 = "1.6.8"
uiTestManifest = "1.6.8"
uiTooling = "1.6.8"
design-material3 = "1.6.8"
coilCompose = "2.4.0"
constraintlayout = "2.1.4"
material3 = "1.3.2"
materialVersion = "1.12.0"
materialIconsExtended = "1.6.8"

#Firebase
firebaseFirestoreKtx = "25.1.0"
firebaseAuth = "23.0.0"
firebaseAuthKtx = "23.0.0"
firebaseFirestore = "25.1.0"

# Credentials
credentials = "1.3.0"
googleid = "1.1.1"

# Networking
okhttp = "4.12.0"
retrofit = "2.9.0"
json-ser = "1.6.0"

#Google Service
playServicesAuth = "21.2.0"

#MapBox
mapbox = "11.15.2"
mapboxNavigation = "3.16.0-beta.1"

# Plugins
json = "20240303"

#Retrofit and Moshi
retrofit2 = "2.11.0"
moshi-kotlin = "1.15.1"
converter-moshi= "2.11.0"

# Testing Unit
junit = "4.13.2"
mockitoCore = "5.13.0"
mockitoKotlin = "5.4.0"
mockk = "1.13.10"
corountineKotlin = "1.7.3"

# Testing UI
espressoCore = "3.6.1"
junitVersion = "1.2.1"
kaspresso = "1.5.5"
kaspressoAllureSupport = "1.4.3"
kaspressoComposeSupport = "1.5.5"
mockkAgent = "1.13.10"
mockkAndroid = "1.13.10"
navigationCompose = "2.7.7"
robolectric = "4.11.1"
espressoContrib = "3.6.1"
exifinterface = "1.3.7"
orchestrator = "1.5.0"

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
# UI tools
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }

# UI Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-design-material3 = {group = "androidx.compose.material", name = "material-icons-extended", version.ref ="design-material3"}
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref ="ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
compose-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
coil-compose = {group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose"}
# Plugins
json = { module = "org.json:json", version.ref = "json" }


## Firebase BoM
firebaseBom = { module = "com.google.firebase:firebase-bom", version = "34.3.0"}
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }

## Credentials Manager
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

## Google Services
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

## OkHTTP packages
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

## SBB API
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
xmlconverter = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "retrofit" }

# JSON
jsonserialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json-ser"}

## MapBox packages
mapbox-maps = {module = "com.mapbox.maps:android-ndk27", version.ref = "mapbox"}
mapbox-maps-compose = {module = "com.mapbox.extension:maps-compose-ndk27", version.ref ="mapbox"}
mapbox-maps-navigation = {module = "com.mapbox.navigationcore:android-ndk27", version.ref ="mapboxNavigation"}

## Retrofit and Moshi
retrofit2 = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2"}
moshikotlin = {module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin"}
convertermoshi = {module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi"}

## Testing Unit
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin" , version.ref="mockitoKotlin"}
coroutines-kotlin = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref ="corountineKotlin"}
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
## Testing UI
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoContrib" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
kaspresso = { module = "com.kaspersky.android-components:kaspresso", version.ref = "kaspresso" }
kaspresso-allure-support = { module = "com.kaspersky.android-components:kaspresso-allure-support", version.ref = "kaspressoAllureSupport" }
kaspresso-compose-support = { module = "com.kaspersky.android-components:kaspresso-compose-support", version.ref = "kaspressoComposeSupport" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationCompose" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationCompose" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoCore" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockkAgent" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
kaspresso-compose = { group = "com.kaspersky.android-components", name = "kaspresso-compose-support", version.ref = "kaspresso" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
sonar = { id = "org.sonarqube", version.ref = "sonar" }
## Google Services and Firebase setup
gms = {id = "com.google.gms.google-services", version.ref= "gms"}
